id: P001829
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN3408
  title: འཕགས་ཡུལ་རྒྱན་དྲུག་མཆོག་གཉིས་ཀྱི་ཞལ་ལུང་།
  author: ''
  volumes:
    a9796e5962b74537b10a1a7f68b40145:
      image_group_id: I3CN4390
      title: ''
      volume_number: 1
      total_pages: 273
      base_file: v001.txt
    800b801afdd74222b65c32fd6dd01696:
      image_group_id: I3CN4391
      title: ''
      volume_number: 2
      total_pages: 439
      base_file: v002.txt
    00026a1a1813467ca61c83ecf9cae7c1:
      image_group_id: I3CN4392
      title: ''
      volume_number: 3
      total_pages: 493
      base_file: v003.txt
    68db0e67b09048fa9a0cbde6207ae57c:
      image_group_id: I3CN4393
      title: ''
      volume_number: 4
      total_pages: 385
      base_file: v004.txt
    84cf697d8d644ede879f2df799a2d65c:
      image_group_id: I3CN4394
      title: ''
      volume_number: 5
      total_pages: 421
      base_file: v005.txt
    1c51654498854d24ad1e9a21c2417c57:
      image_group_id: I3CN4395
      title: ''
      volume_number: 6
      total_pages: 341
      base_file: v006.txt
    eb047ef37cd84dd0a91182a4493cbf7a:
      image_group_id: I3CN4396
      title: ''
      volume_number: 7
      total_pages: 425
      base_file: v007.txt
    baf056a6e7334d8194f5b93d9a8714f2:
      image_group_id: I3CN4397
      title: ''
      volume_number: 8
      total_pages: 471
      base_file: v008.txt
    86e531626edf4243b4a7aee3c32da5cc:
      image_group_id: I3CN4398
      title: ''
      volume_number: 9
      total_pages: 461
      base_file: v009.txt
    331e7ae5d7f04887894cba564a4e0f54:
      image_group_id: I3CN4399
      title: ''
      volume_number: 10
      total_pages: 633
      base_file: v010.txt
    8c48a5154b9b452fa1cc072933cf95f4:
      image_group_id: I3CN4400
      title: ''
      volume_number: 11
      total_pages: 569
      base_file: v011.txt
    5d749318590b47ceb2428f01838d8e26:
      image_group_id: I3CN4401
      title: ''
      volume_number: 12
      total_pages: 401
      base_file: v012.txt
    203154a488e54ad3acfa62f4ac5c7bee:
      image_group_id: I3CN4402
      title: ''
      volume_number: 13
      total_pages: 433
      base_file: v013.txt
    ef6cb4105e504c63aaf9248168104b28:
      image_group_id: I3CN4403
      title: ''
      volume_number: 14
      total_pages: 369
      base_file: v014.txt
    eb22cc93f6dc416caf03c579aa597341:
      image_group_id: I3CN4404
      title: ''
      volume_number: 15
      total_pages: 605
      base_file: v015.txt
    006a1dcbdf934a42b5d2d4344305c5b2:
      image_group_id: I3CN4405
      title: ''
      volume_number: 16
      total_pages: 463
      base_file: v016.txt
    662b207597fd41479ef9b73d2b8d7ace:
      image_group_id: I3CN4406
      title: ''
      volume_number: 17
      total_pages: 434
      base_file: v017.txt
    cc54153dab5f42309a68491ca905b97c:
      image_group_id: I3CN4407
      title: ''
      volume_number: 18
      total_pages: 393
      base_file: v018.txt
    a29c161719a34fbcbfb2e3349d88c7a8:
      image_group_id: I3CN4408
      title: ''
      volume_number: 19
      total_pages: 481
      base_file: v019.txt
    070f2e0071294ebc80794f6784f35b10:
      image_group_id: I3CN4409
      title: ''
      volume_number: 20
      total_pages: 433
      base_file: v020.txt
    9f69a6f54f584232b0caa8f3f2824fd6:
      image_group_id: I3CN4410
      title: ''
      volume_number: 21
      total_pages: 608
      base_file: v021.txt
    8ebb7223df3d49cbb26b686447fdcb1c:
      image_group_id: I3CN4411
      title: ''
      volume_number: 22
      total_pages: 529
      base_file: v022.txt
    7935d4ce31c3474399275f89d1b96a6e:
      image_group_id: I3CN4412
      title: ''
      volume_number: 23
      total_pages: 504
      base_file: v023.txt
    979a5b4d4c94417da4a76fa9b142977d:
      image_group_id: I3CN4413
      title: ''
      volume_number: 24
      total_pages: 521
      base_file: v024.txt
    b1792db2ce174864bc9cbf8d6079fd82:
      image_group_id: I3CN4414
      title: ''
      volume_number: 25
      total_pages: 605
      base_file: v025.txt
    3a91cecc79ae44bfa4275af943b2474f:
      image_group_id: I3CN4415
      title: ''
      volume_number: 26
      total_pages: 737
      base_file: v026.txt
    80b700787a6e4e1d8ccadff9ee3ec2ba:
      image_group_id: I3CN4416
      title: ''
      volume_number: 27
      total_pages: 657
      base_file: v027.txt
    577a57f35bd549818011edb78557afc4:
      image_group_id: I3CN4417
      title: ''
      volume_number: 28
      total_pages: 597
      base_file: v028.txt
    501456334bcf4bb5823becb7e5bfde88:
      image_group_id: I3CN4418
      title: ''
      volume_number: 29
      total_pages: 457
      base_file: v029.txt
    017436440b114da3aef8741f1858161f:
      image_group_id: I3CN4419
      title: ''
      volume_number: 30
      total_pages: 457
      base_file: v030.txt
    dfeb98acc3274332aa64971a37944472:
      image_group_id: I3CN4420
      title: ''
      volume_number: 31
      total_pages: 437
      base_file: v031.txt
    28924166daa348b186fb05b56231f179:
      image_group_id: I3CN4421
      title: ''
      volume_number: 32
      total_pages: 535
      base_file: v032.txt
    36bca82177a74b5191f1a154a1f24c63:
      image_group_id: I3CN4422
      title: ''
      volume_number: 33
      total_pages: 369
      base_file: v033.txt
    2c402e2e9f8147c195cb60ae3dde3987:
      image_group_id: I3CN4423
      title: ''
      volume_number: 34
      total_pages: 636
      base_file: v034.txt
    ec76255c67404787945141b759de9a14:
      image_group_id: I3CN4424
      title: ''
      volume_number: 35
      total_pages: 477
      base_file: v035.txt
    1173f69615054686a774404913f93ca5:
      image_group_id: I3CN4425
      title: ''
      volume_number: 36
      total_pages: 489
      base_file: v036.txt
    9fb1c2f59e3143bb9e6061692aeab5a9:
      image_group_id: I3CN4426
      title: ''
      volume_number: 37
      total_pages: 457
      base_file: v037.txt
    c227d43c2ae5473cb1a575b28326b22a:
      image_group_id: I3CN4427
      title: ''
      volume_number: 38
      total_pages: 477
      base_file: v038.txt
    6f1f38a928724b25805d675b5c220415:
      image_group_id: I3CN4428
      title: ''
      volume_number: 39
      total_pages: 285
      base_file: v039.txt
    aa2ed0633ae847bbaf4f932ac167c703:
      image_group_id: I3CN4429
      title: ''
      volume_number: 40
      total_pages: 307
      base_file: v040.txt
    b4c5f5ed72974ff9b25ae3b3f7d25632:
      image_group_id: I3CN4430
      title: ''
      volume_number: 41
      total_pages: 553
      base_file: v041.txt
    bf7911a0bfc441919dfc78f5109052fe:
      image_group_id: I3CN4431
      title: ''
      volume_number: 42
      total_pages: 509
      base_file: v042.txt
    700fb282c41c4f4fa4721f259f872aa2:
      image_group_id: I3CN4432
      title: ''
      volume_number: 43
      total_pages: 397
      base_file: v043.txt
    24b2b0c4ed36453b8aab0b46d60ee10b:
      image_group_id: I3CN4433
      title: ''
      volume_number: 44
      total_pages: 573
      base_file: v044.txt
    bf5fb84739714d8f83cb2fd9de931627:
      image_group_id: I3CN4434
      title: ''
      volume_number: 45
      total_pages: 469
      base_file: v045.txt
    dcae631324b64f63ba640fbe8d63bcd3:
      image_group_id: I3CN4435
      title: ''
      volume_number: 46
      total_pages: 511
      base_file: v046.txt
    9e9d73682874476b8a69126882177bdd:
      image_group_id: I3CN4436
      title: ''
      volume_number: 47
      total_pages: 537
      base_file: v047.txt
    ff15c0cc66d44a439b0424ca9e913cbe:
      image_group_id: I3CN4437
      title: ''
      volume_number: 48
      total_pages: 557
      base_file: v048.txt
    c64cfcec2c8a4243b10b38ce0624335d:
      image_group_id: I3CN4438
      title: ''
      volume_number: 49
      total_pages: 459
      base_file: v049.txt
    bf7a5ab208f446fb8d284e5169b208d9:
      image_group_id: I3CN4439
      title: ''
      volume_number: 50
      total_pages: 385
      base_file: v050.txt
    d40b8a69ab1d4f5db788260f19d7b3b4:
      image_group_id: I3CN4440
      title: ''
      volume_number: 51
      total_pages: 341
      base_file: v051.txt
    1c0edb3ac916462a9d3f285fc2532e2b:
      image_group_id: I3CN4441
      title: ''
      volume_number: 52
      total_pages: 603
      base_file: v052.txt
    59bbbaa56305421f94f029ff8de717a7:
      image_group_id: I3CN4442
      title: ''
      volume_number: 53
      total_pages: 597
      base_file: v053.txt
    3923c5028e794bd1a77b0f409676cd5b:
      image_group_id: I3CN4443
      title: ''
      volume_number: 54
      total_pages: 302
      base_file: v054.txt
    e487da2aeb634f2b91c448418f5d717f:
      image_group_id: I3CN4444
      title: ''
      volume_number: 55
      total_pages: 431
      base_file: v055.txt
    b5e00d5b0d9848a3a89e80a5647da6c6:
      image_group_id: I3CN4445
      title: ''
      volume_number: 56
      total_pages: 609
      base_file: v056.txt
    66a162971c664b8eb35a35c8ba74005c:
      image_group_id: I3CN4446
      title: ''
      volume_number: 57
      total_pages: 377
      base_file: v057.txt
    4e9f6edecc854a03a2871893c5b5ee7a:
      image_group_id: I3CN4447
      title: ''
      volume_number: 58
      total_pages: 368
      base_file: v058.txt
    d06e933d65914cd4914693ca32d0dd45:
      image_group_id: I3CN4448
      title: ''
      volume_number: 59
      total_pages: 391
      base_file: v059.txt
    854723ed6de9454e8267853f5d84f2ad:
      image_group_id: I3CN4449
      title: ''
      volume_number: 60
      total_pages: 133
      base_file: v060.txt
    f387215eaaca42bcb7a843ab46695366:
      image_group_id: I3CN4450
      title: ''
      volume_number: 61
      total_pages: 403
      base_file: v061.txt
    045f4fe48fe5417c9e5d7302cb19629b:
      image_group_id: I3CN4451
      title: ''
      volume_number: 62
      total_pages: 403
      base_file: v062.txt
    141a6fe0c49548d0a8ad9c9020ad95b9:
      image_group_id: I3CN4452
      title: ''
      volume_number: 63
      total_pages: 437
      base_file: v063.txt
    944020429454410eabb45cea899f0df5:
      image_group_id: I3CN4453
      title: ''
      volume_number: 64
      total_pages: 453
      base_file: v064.txt
    31ffa08c354747f0bc6fe61a1b082ee2:
      image_group_id: I3CN4454
      title: ''
      volume_number: 75
      total_pages: 551
      base_file: v065.txt
    5c57222dae32464da24e59f4addc0884:
      image_group_id: I3CN4455
      title: ''
      volume_number: 66
      total_pages: 535
      base_file: v066.txt
    914cb2452ce4482eaefb15abc8551854:
      image_group_id: I3CN4456
      title: ''
      volume_number: 67
      total_pages: 551
      base_file: v067.txt
    ebf5e7d4d1b14cc992edefcbbb84b2ee:
      image_group_id: I3CN4457
      title: ''
      volume_number: 68
      total_pages: 419
      base_file: v068.txt
    706aa75e129d4cb3b54d470e28c5de2c:
      image_group_id: I3CN4458
      title: ''
      volume_number: 69
      total_pages: 413
      base_file: v069.txt
    3dde56edb7a646c2b0efc2212f4a406e:
      image_group_id: I3CN4459
      title: ''
      volume_number: 70
      total_pages: 541
      base_file: v070.txt
    89d45882365e4c4d923d9df5d3478913:
      image_group_id: I3CN4460
      title: ''
      volume_number: 71
      total_pages: 550
      base_file: v071.txt
    24a4bba9c77a4243a5ef86c6ddc463ab:
      image_group_id: I3CN4461
      title: ''
      volume_number: 72
      total_pages: 423
      base_file: v072.txt
    cc7c6a4d03a24e2bbede3ff5e25d4f6b:
      image_group_id: I3CN4462
      title: ''
      volume_number: 73
      total_pages: 565
      base_file: v073.txt
    562657de484d4086b9f356c20833fef3:
      image_group_id: I3CN4463
      title: ''
      volume_number: 74
      total_pages: 0
    4ecf4bb67a024c928bba9bec2433b44f:
      image_group_id: I3CN4464
      title: ''
      volume_number: 65
      total_pages: 466
      base_file: v074.txt
    a20280a7d937437e9aef1d38b9ebec4c:
      image_group_id: I3CN4465
      title: ''
      volume_number: 76
      total_pages: 797
      base_file: v075.txt
    4afe1ffbd50a4d918b2d63961563690f:
      image_group_id: I3CN4466
      title: ''
      volume_number: 77
      total_pages: 409
      base_file: v076.txt
    8b8b40fae81149cf8b2b0ea40b5b6560:
      image_group_id: I3CN4467
      title: ''
      volume_number: 78
      total_pages: 521
      base_file: v077.txt
    25e636bbf3f6419da03ec6051ead2338:
      image_group_id: I3CN4468
      title: ''
      volume_number: 79
      total_pages: 431
      base_file: v078.txt
    3610d97d6dc54e1f992b93b351e26d6a:
      image_group_id: I3CN4469
      title: ''
      volume_number: 80
      total_pages: 18
      base_file: v079.txt
